import type { BlockNode, BlockRenderContext, InlineSpan } from "../types";
import { parseDslToBlocks } from "./parser";
import { getBlock, getCombinedBlockStyles } from "../registry";

export interface RenderDocumentResult {
  html: string;
  blocks: BlockNode[];
  jsonLd: {
    "@context": "https://schema.org";
    "@graph": any[];
  };
  styles: string;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** The `download` attribute of a link: absent, bare, or naming the file. */
function formatDownloadAttr(value: unknown): string {
  if (value === undefined || value === null || value === false || value === "") return "";
  if (value === true) return " download";
  return ` download="${escapeHtml(String(value))}"`;
}

function renderInlineSpans(
  children: (BlockNode | InlineSpan)[],
  serverDataMap: Map<string, any>,
  ctx?: BlockRenderContext
): string {
  return children
    .map((child) => {
      if ("type" in child && child.type !== "text") {
        return renderBlockNodeSync(child as BlockNode, serverDataMap, ctx);
      }
      const inline = child as InlineSpan;
      let text = escapeHtml(inline.text || "");
      const marks = inline.marks || [];
      const markDefs = inline.markDefs || [];

      for (const mark of marks) {
        if (mark === "bold") text = `<strong>${text}</strong>`;
        else if (mark === "italic") text = `<em>${text}</em>`;
        else if (mark === "strike") text = `<del>${text}</del>`;
        else if (mark === "code") text = `<code class="prose-inline-code">${text}</code>`;
        else if (mark === "underline") text = `<u>${text}</u>`;
      }

      for (const def of markDefs) {
        if (def.type === "link") {
          const href = escapeHtml(def.attrs?.href || "#");
          const target = def.attrs?.target ? ` target="${escapeHtml(String(def.attrs.target))}"` : "";
          const rel = def.attrs?.rel ? ` rel="${escapeHtml(String(def.attrs.rel))}"` : "";
          const download = formatDownloadAttr(def.attrs?.download);
          text = `<a href="${href}"${target}${rel}${download} class="prose-link">${text}</a>`;
        }
      }

      return text;
    })
    .join("");
}

function renderBlockNodeSync(node: BlockNode, serverDataMap: Map<string, any>, ctx?: BlockRenderContext): string {
  const blockDef = getBlock(node.type);
  const data = serverDataMap.get(node.id);

  let childrenHtml = "";
  if (node.children && node.children.length > 0) {
    const isInlineOnly = node.children.every((c) => "type" in c && (c as any).type === "text");
    if (isInlineOnly) {
      childrenHtml = renderInlineSpans(node.children, serverDataMap, ctx);
    } else {
      childrenHtml = node.children
        .map((c) => {
          if ("type" in c && c.type !== "text") {
            return renderBlockNodeSync(c as BlockNode, serverDataMap, ctx);
          }
          return escapeHtml((c as InlineSpan).text || "");
        })
        .join("\n");
    }
  }

  if (blockDef?.render) {
    return blockDef.render(node.props, childrenHtml, data, ctx);
  }

  // Fallback generic container
  return `<div class="block-${node.type}">${childrenHtml}</div>`;
}

/**
 * Traverses a block tree recursively to collect promises for loadServerData.
 */
async function loadAllServerData(
  nodes: BlockNode[],
  ctx: BlockRenderContext,
  map: Map<string, any>
): Promise<void> {
  const tasks: Promise<void>[] = [];

  function traverse(node: BlockNode) {
    const blockDef = getBlock(node.type);
    if (blockDef?.loadServerData) {
      tasks.push(
        blockDef.loadServerData(node.props, ctx).then((res) => {
          map.set(node.id, res);
        })
      );
    }
    if (node.children) {
      for (const child of node.children) {
        if ("type" in child && child.type !== "text") {
          traverse(child as BlockNode);
        }
      }
    }
  }

  nodes.forEach(traverse);
  await Promise.all(tasks);
}

/**
 * Collects all JSON-LD entities generated by blocks in the document.
 */
function collectJsonLdEntities(nodes: BlockNode[], map: Map<string, any>): any[] {
  const entities: any[] = [];

  function traverse(node: BlockNode) {
    const blockDef = getBlock(node.type);
    if (blockDef?.generateJsonLd) {
      const data = map.get(node.id);
      const res = blockDef.generateJsonLd(node.props, data);
      if (res) {
        if (Array.isArray(res)) entities.push(...res);
        else entities.push(res);
      }
    }
    if (node.children) {
      for (const child of node.children) {
        if ("type" in child && child.type !== "text") {
          traverse(child as BlockNode);
        }
      }
    }
  }

  nodes.forEach(traverse);
  return entities;
}

/**
 * High-performance, unified document renderer for both Live Draft Preview and Production.
 */
export async function renderDocument(
  content: string | BlockNode[],
  ctx: BlockRenderContext = {}
): Promise<RenderDocumentResult> {
  const blocks = typeof content === "string" ? parseDslToBlocks(content) : content;
  const serverDataMap = new Map<string, any>();

  // 1. Asynchronously load server-side data (e.g. RelatedPosts querying D1)
  await loadAllServerData(blocks, ctx, serverDataMap);

  // 2. Synthesize JSON-LD Schema entities
  const blockEntities = collectJsonLdEntities(blocks, serverDataMap);

  // Base BlogPosting entity
  const post = ctx.post;
  const blogPosting: any = {
    "@type": "BlogPosting",
    "@id": post?.slug ? `#article-${post.slug}` : "#article",
    headline: post?.title || "",
    author: {
      "@type": "Person",
      name: post?.author || "jeflopo",
    },
  };

  if (blockEntities.length > 0) {
    blogPosting.mentions = blockEntities
      .filter((e) => e["@id"])
      .map((e) => ({ "@id": e["@id"] }));
  }

  const jsonLd = {
    "@context": "https://schema.org" as const,
    "@graph": [blogPosting, ...blockEntities],
  };

  // 3. Render HTML blocks
  const htmlParts = blocks.map((b) => renderBlockNodeSync(b, serverDataMap, ctx));
  const html = htmlParts.join("\n\n");

  // 4. Collect CSS styles
  const styles = getCombinedBlockStyles();

  return {
    html,
    blocks,
    jsonLd,
    styles,
  };
}
